name: run nosetests
on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  strategy:
    # Ensure that a wheel builder finishes even if another fails
    fail-fast: false
    matrix:
      # Github Actions doesn't support pairing matrix values together, let's improvise
      # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
      buildplat:
        - [ ubuntu-20.04, manylinux_x86_64 ]
        - [ ubuntu-20.04, musllinux_x86_64 ]
        - [ macos-10.15, macosx_* ]
        - [ windows-2019, win_amd64 ]
        - [ windows-2019, win32 ]
      #        spacy doesn't compile win32
      #        python: ["cp36"] # Note: Wheels not needed for PyPy
      python-version: [ "cp36", "cp37", "cp38", "cp39", "cp310" ] # Note: Wheels not needed for PyPy
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    if: >-
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'Build System'))
    runs-on: ${{ matrix.buildplat[0] }}
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: nose tests
        run: |
          python --version
          python setup.py build_ext --inplace
          nosetests


  

